### PR TITLE
Better scraping

### PR DESCRIPTION
**Pull request by Uzay-G**
Uses [python-readability](https://github.com/buriy/python-readability) for better scraping.

Notably articles saved with this method have much less noise / only post content is saved.

### CODE REVIEW

**Comment by Uzay-G** [comment]
This PR is a WIP and readability-lxml still has to be investigated to see if it fits Archivy's needs.

**Comment by Uzay-G** [comment]
@edditler do you think using readability should be an option you can disable or it's good enough to just make it the archival process.

**Comment by edditler** [comment]
> @edditler do you think using readability should be an option you can disable or it's good enough to just make it the archival process.

I'd just use it as the default. Works almost perfectly and much better than the previous solution.

**Comment by Uzay-G** [comment]
Alright, perfect!

**Pull request merged**
