### PR TITLE
Restructure api

### PR DESCRIPTION
**Pull request by Uzay-G**
This pr:

    - restructures the api by clearly separating views in routes.py and
    api.py
    - adds a login for api routes
    - documents the api in a new API.md file

I'd appreciate a review of these changes @clemux @srevinsaju.

Thanks!

### CODE REVIEW

**Review by srevinsaju — COMMENTED** [review]
Did a code review. Looks good. I will try running it now

**Comment by srevinsaju** [comment]
Tested, looks good. I am not much familiar with the API. @clemux is the right person anyway :smile:

**Comment by Uzay-G** [comment]
Yup it'd be great if you could take a look @clemux :)

**Comment by Uzay-G** [comment]
Once this has been reviewed and merged, we can go further with #123

**Pull request merged**
