### PR TITLE
Use better server for running archivy in production

### LINKED ISSUE #170: Do not use app.run in production.
as [per the flask docs](https://flask.palletsprojects.com/en/1.1.x/deploying/)  and the warning that should be shown when running, you should not use the development server in production which is what `archivy run` will start. 

the development server is very insecure, has a low performance and of generally bad. it should only run when actually developing the app.

### PR DESCRIPTION
**Pull request by Uzay-G**
Fixes #170 by using [gunicorn](https://gunicorn.org]

Introduces an efficient, more suited webserver for the application.

### CODE REVIEW

**Comment by Uzay-G** [comment]
@srevinsaju what do you think of the code here?

The way the gunicorn function works requires a lot of boilerplate (seen in pr) but I'm not sure if I should put the class elsewhere.

**Comment by Uzay-G** [comment]
[Some people](https://www.reddit.com/r/selfhosted/comments/kocu1i/archivy_is_a_selfhosted_knowledge_repository_that/ghqe8kd?utm_source=share&utm_medium=web2x&context=3) also recommended changing the default port.

I need to think about this.

**Comment by srevinsaju** [comment]
I do not agree with this patch. Nothing should be made default.

**Comment by Uzay-G** [comment]
> I do not agree with this patch. Nothing should be made default.

What do you mean?

This patch is introduced to fix this specific problem (not related to ports):

- The `archivy run` program currently launches a flask development server which is inefficient and unsuited for production. This patch fixes the command to use a production-ready webserver

**Comment by srevinsaju** [comment]
No, but `archivy run` should use a flask debug server, not `gunicorn`. Those who would like to deploy archivy to the world wide web should manually use gunicorn like


```bash
gunicorn archivy.wsgi
```

The `wsgi` wrapper should not be triggered otherwise.

**Comment by srevinsaju** [comment]
I'm worried. The code quality of `archivy` is going down, making it less maintainable in future, for example.. if you stop working on this project, it becomes impossible to maintain it.

**Comment by Uzay-G** [comment]
Do you mean that we shouldn't introduce a good default?

I don't see the advantages of using the flask development server, but anyways if we don't provide a production default we need to document how one can run it - because it's actually not very obvious in archivy's case.

**Comment by Uzay-G** [comment]
> I'm worried. The code quality of `archivy` is going down, making it less maintainable in future, for example.. if you stop working on this project, it becomes impossible to maintain it.

I see what you mean. By code quality do you mean the introduction of new tools? It is true that it should not become too complex...

Alright, this is what I think I will do. Instead of replacing the webserver - I think there **needs** to be documentation on options to host it in production.

**Comment by Uzay-G** [comment]
I appreciate your feedback. I will not go forward with PR but it is essential that archivy documents that the dev server should **not** be used for people wanting to scale their instance.

**Comment by srevinsaju** [comment]
I have a detailed reply, I need some time to properly write it.

**Comment by Uzay-G** [comment]
Ok no problem. I'm very happy about your input - the reason I maybe acted a bit rashly is that archivy was recently posted to a large subreddit (by someone else) where it has done very well but also caused many questions and input that I was a bit sidetracked by.

**Comment by Uzay-G** [comment]
Please tell me if there are other occurrences where you think i didn't go the best route - discussing thing is always best.

**Comment by laundmo** [comment]
as the person who originally raised the issue: i dont think you should be looking for a python way to do this. (unless you can switch from Flask to Quart) WSGI servers are supposed to invoke the pyhton code, not the other way around.

In my opinion: rename the `run` command to `develop` to make it very clear its not meant for production, and provide information and documentation (and maybe even a docker container) to run in production, possibly without the need for a CLI at all, allowing everything the CLI does to be done through config files or environment variables.

**Comment by srevinsaju** [comment]
Its relatively simpler than your patch.

I am running `archivy` on my home server like this:
Add a file `archivy/wsgi.py`

```python
from archivy import app as application

def run():
    print("Running archivy.wsgi")
    load_dotenv()

    application.run()


if __name__ == "__main__":
    run()

```

Run `gunicorn archivy.wsgi` to run the gunicorn server.


You might be like, "Why do we not enable it by default then?"

Take a look at the [Django's documentation](https://docs.djangoproject.com/en/3.1/). They each you to use the development server. They know its unsafe, they let the user know its unsafe. Why? Because, they want the users to be responsible at what they are doing. We should not make things easy, so that it gets running on a public webserver, where the users have no clue what they are doing. `gunicorn` is not the best webserver either. Binding a tool to a project makes it barely usable in future.


Okay, second: "Srevin, if you knew how to deploy it to production, why did you not create a PR?"
Two reasons:
* `gunicorn` is used for multi threaded async requests, and better security than the flask server. My use case for the home server was the 'multi threaded async requests', running 4 threads on archivy. But... what about security? 
* Creating a PR to include `gunicorn` support might tend to make users feel confident of deploying archivy to their server. However, `archivy` has tonnes of security vulnerabilities. I was thinking of deploying it to the public server, but then, I had to read the archivy source code to make sure that its safe. But then, I found several XSS vulnerabilities, which might expose a private server. So, yes.. Archivy is not yet ready for production.

I am manually patching all the security vulnerabilities to a local `develop` branch. Unfortunately, I do not have enough time for PRs, reviews and writing tests. Tests are good, but however they could come after code quality and maintainability. 



> Ok no problem. I'm very happy about your input - the reason I maybe acted a bit rashly with this PR is that archivy was recently posted to a large subreddit (by someone else) where it has done very well but also caused many questions and input that I was a bit sidetracked by.

I appreciate that. I appreciate the work you are putting in, I like the way you wish to add features to archivy. But, as a rule of thumb, the amount of features is always accompanied by bugs, security vulnerabilities. Thats why, even with such a huge number of contributors, KDE is unstable, compared to stock GNOME.

 Right now, Archivy can be considered strictly safe for "local" use only. A user _may_ chose to deploy it to production, ONLY AT THEIR OWN RISK.




> Please tell me if there are other occurrences where you think i didn't go the best route - discussing thing is always best.

Agreed.

**Comment by srevinsaju** [comment]
> as the person who originally raised the issue: i dont think you should be looking for a python way to do this. (unless you can switch from Flask to Quart) WSGI servers are supposed to invoke the pyhton code, not the other way around.
> 
> In my opinion: rename the `run` command to `develop` to make it very clear its not meant for production, and provide information and documentation (and maybe even a docker container) to run in production, possibly without the need for a CLI at all, allowing everything the CLI does to be done through config files or environment variables.

I agree, this is the right way of doing it.

**Comment by laundmo** [comment]
> I agree, this is the right way of doing it, but archivy is not yet safe for that.

i was not aware of the security vulnerabilities. since you said you have a local brach to fix the issues, i think it would still be nice for the people developing this to see a PR, even if its lacking the requirements to get it merged, because others might be willing to do those and just to see how the fixes are done.

**Comment by srevinsaju** [comment]
Archivy is still very safe to be run at `127.0.0.1`. With a simple firewall like `ufw`, nothing nasty would happen. Even without a firewall, as long as you trust people on your home network, nothing bad is going to happen. As `archivy` is open source, people can easily look up the security vulnerabilities and attack them at the right spot. 

But fixing security vulnerabilities would come after increasing code maintainability. Code maintainability is not about using external libraries. Code maintainability is solely based on the quality of code written. Right now, we _only_ follow code standards like PEP, not coding styles. A complete restructure of the archivy idea in better maintainable code will result in a fork, a write from scratch or 2-3 years.

**Comment by srevinsaju** [comment]
> > I agree, this is the right way of doing it, but archivy is not yet safe for that.
> 
> i was not aware of the security vulnerabilities. since you said you have a local brach to fix the issues, i think it would still be nice for the people developing this to see a PR, even if its lacking the requirements to get it merged, because others might be willing to do those and just to see how the fixes are done.

Sure, I only do not want the project to split, like many others.

**Comment by Uzay-G** [comment]
I see.

For the vulnerabilities you mention, I assume they are all in the rendering of markdown (whether in the search results or the actual renderer). These issues are all then behind the login wall - the user must not give access to untrusted users, as mentioned in the docs:

> If you'd like to add users, you can simply create new admin users with the create-admin command. Only give credentials to trusted people.

I would like to see your work on this but this is the reason i have not looked too much into vulnerabilities - hosting an archivy instance imo is safe, what's dangerous would be giving credentials.

**Comment by Uzay-G** [comment]
> But fixing security vulnerabilities would come after increasing code maintainability. Code maintainability is not about using external libraries. Code maintainability is solely based on the quality of code written. Right now, we only follow code standards like PEP, not coding styles. A complete restructure of the archivy idea in better maintainable code will result in a fork, a write from scratch or 2-3 years.

Ouch. Could you specify exactly what is wrong in the current way archivy is structured? I have modularised the code and defined a clear overview of the way one can interact with the python API [here](https://archivy.github.io).

I do not see how making the code fit to a better coding style would take 2-3 years.

**Comment by srevinsaju** [comment]
> I see.
> 
> For the vulnerabilities you mention, I assume they are all in the rendering of markdown (whether in the search results or the actual renderer). These issues are all then behind the login wall - the user must not give access to untrusted users, as mentioned in the docs:
> 
> > If you'd like to add users, you can simply create new admin users with the create-admin command. Only give credentials to trusted people.
> 
> I would like to see your work on this but this is the reason i have not looked too much into vulnerabilities - hosting an archivy instance imo is safe, what's dangerous would be giving credentials.

Yes, but still not safe

Archivy does not have 
* 2FA
* Rate limiting

Anyone can try entering the password many times, right? Have you implemented rate limiting? 

Archivy does not check the strength of the new password, ideally it should not accept passwords less than 8 characters, and having only digits or numbers, and should require atleast a non-alphanumeric character. We need to fix that first

**Comment by Uzay-G** [comment]
Good idea. I had thought of this but never implemented it for lack of time :sweat:

**Comment by srevinsaju** [comment]
> > But fixing security vulnerabilities would come after increasing code maintainability. Code maintainability is not about using external libraries. Code maintainability is solely based on the quality of code written. Right now, we only follow code standards like PEP, not coding styles. A complete restructure of the archivy idea in better maintainable code will result in a fork, a write from scratch or 2-3 years.
> 
> Ouch. Could you specify exactly what is wrong in the current way archivy is structured? I have modularised the code and defined a clear overview of the way one can interact with the python API [here](https://archivy.github.io).
> 
> I do not see how making the code fit to a better coding style would take 2-3 years.

Happy to explain.

Better coding style, the art of computer programming, includes techniques like Object Oriented Programming, functional programming, template metaprogramming, event-driven, real-time, multithreaded, dependency injection. It might take years to learn this structures, As you said, you might not like the code you have written 2 years ago, just like that, you will slowly learn new techniques under a mentor, which will make you feel like rewriting the code 2 years later. I used to write the code, similar to what you have written 5-6 months ago. So, that difference is the gap, I said of 2 years or so.

image

Archivy maintainability is `D`, So, getting from D to A+ will be a long run. Tested on 2e98de1 `master`. 

Until now, `archivy` is going in the right path. We are improving local user experience first, and at last we perfected most of it, which would get featured in v1.0. We will perfect security in v2.0, and by v3.0 Archivy should be publicly hosted. 


## v1.0
- [x] Markdown editor
- [x] User Interface
- [ ] Lunr client side search (safer)

## v2.0
- [ ] 2FA 
- [ ] Rate limiting
- [ ] Email Recovery support
- [ ] SMTP / IMAP support, verify users by email address, invite users by email address, invite by link.
- [ ] Mobile App (PWA, offline support)
- [ ] Desktop client (A userfriendly, QT, GTK app, which does not require user to know how to type commands in a terminal)
- [ ] More hook support
- [ ] AppImage, .exe for Windows, DMG

## v3.0
- [ ] Decentralization
- [ ]  Federation
- [ ]  Automatic push GitHub, GitLab (automatic)
- [ ] Static site generation
- [ ] Provide standalone binary releases (no python needed) to make server deployment easy
- [ ] Add view only support, No auth.
- [ ] Support to share to social media.
- [ ] Encrypted share link (expires within, n days, password protected, link only shares)
- [ ] User level logs, track all changes by username / email address

**Comment by laundmo** [comment]
im always skeptical of tools that are supposed to show code quality or maintainability.

personally, i choose to go by much simpler measures, which are mostly strict limits for locals per func, globaps per module and a maccabe complexity of under 10

**Comment by Uzay-G** [comment]
Yes I'm curious by what standard you found this metric. I'd say there are
some problems in certain pieces of archivy code that need to be refactored
but it does not deserve a D.

Btw: archivy s git extension does support automatic push.

**Comment by Uzay-G** [comment]
Also you said it took you 6 months to attain this "level", so I don't
understand your estimate of 2 years.

**Comment by srevinsaju** [comment]
> Yes I'm curious by what standard you found this metric. I'd say there are some problems in certain pieces of archivy code that need to be refactored but it does not deserve a D. Btw: archivy s git extension does support automatic push.

1. McCabe Complexity (10)
2. Code Duplication

**Comment by srevinsaju** [comment]
> Also you said it took you 6 months to attain this "level", so I don't understand your estimate of 2 years.


No, I haven't reached that "level" either. I have seen professional programmers at that level. I wish I could code like them.

**Comment by srevinsaju** [comment]
Attaching logs for reference, regarding complexity. 

[log,txt](https://github.com/archivy/archivy/files/5760851/log.txt)

**Comment by srevinsaju** [comment]
> Yes I'm curious by what standard you found this metric. I'd say there are some problems in certain pieces of archivy code that need to be refactored but it does not deserve a D. Btw: archivy s git extension does support automatic push.

Oh cool! I will check that box. Feel free to check the other boxes once you are done. That roadmap is something I thought of, but please feel free to move things from one version to another. :innocent:

**Comment by laundmo** [comment]
You should probably put that Road Map into GitHub projects or something like that

**Comment by srevinsaju** [comment]
> You should probably put that Road Map into GitHub projects or something like that

Agreed, GitHub Projects, and GitHub milestones would help users identify what is the status of the project. What do you think @Uzay-G ?

**Comment by Uzay-G** [comment]
Running th 

> Attaching logs for reference, regarding complexity.
> 
> [log,txt](https://github.com/archivy/archivy/files/5760851/log.txt)

Using radon, that tool, I get an average of A for complexity on the archivy code. I'm confused ...

**Comment by Uzay-G** [comment]
I'm going to close this PR and the issue for now as we think about this.

**Comment by srevinsaju** [comment]
The rest is for duplication. Feel free to sign up for [codeclimate](https://codeclimate.com)

> > Attaching logs for reference, regarding complexity.
> > [log,txt](https://github.com/archivy/archivy/files/5760851/log.txt)
> 
> Using radon, that tool, I get an average of A for complexity on the archivy code. I'm confused ...

**Comment by Uzay-G** [comment]
You know this is very interesting. I used codeclimate - the tool you brought out. And initially got the same result as you.

However, if you had looked at the issues, you would have seen that many of the problems actually stemmed from the analysis of vendored js files / libraries - minified code not written by archivy.

Now I used a pattern to exclude these unrelated js files and this is the true result the archivy code obtained:

image

**Comment by Uzay-G** [comment]
I'm happy the code is not as bad as you thought.

**Comment by srevinsaju** [comment]
Bundling minified third party js was not a good idea after all. Have you added the corresponding LICENSEs to the README? Thanks for bringing it to notice. 

> I'm happy the code is not as bad as you thought.

I am happy too!  :innocent:

**Comment by Uzay-G** [comment]
> Bundling minified third party js was not a good idea after all.

I'd rather do that then use a CDN / npm in this situation. Do you have any other ideas?

**Comment by srevinsaju** [comment]
Can we add a bootstrapping command to `archivy init` which would automatically download the latest minified JS to the directory? What do you think?

Moving to another issue.

**Pull request closed without merging**
