### PR TITLE
Fix possible removal of directories with path traversal

### PR DESCRIPTION
**Pull request by sqrtroot**
At the moment it is still possible to delete directories using relatives path. For example sending a request with the path `../../../../../../../../bin` would delete the /bin folder if you have the permission

### CODE REVIEW

**Comment by Uzay-G** [comment]
I refactored the code a bit, pathlib actually has an `is_relative_to` method that doesn't return a `ValueError`.

**Comment by sqrtroot** [comment]
Yeah correct, is_relative_to exists. But it's a python 3.9 feature. The current version of `python3` on [ubuntu is 3.8](https://packages.ubuntu.com/search?keywords=python3). That's why I created the method is_relative_to. This is based on the method used by is_relative_to in the [Path class](https://github.com/python/cpython/blob/196d4deaf4810a0bba75ba537dd40f2d71a5a634/Lib/pathlib.py#L937-L944).

**Comment by Uzay-G** [comment]
Oh I see, I'll revert that then :sweat_smile:

**Comment by Uzay-G** [comment]
Ok with the new commit it should work. If that's good with you we can merge :+1:

**Comment by sqrtroot** [comment]
lgtm 👍

**Pull request merged**
