### PR TITLE
implement folder renaming; tests; ui; backend; helpers

### PR DESCRIPTION
**Pull request by Uzay-G**
This PR implements a UI / backend to allow users to rename folders, as mentioned in https://github.com/archivy/archivy/issues/191 :

image

@BrianGilbert does this sort of interface / design work for you? Curious to hear your thoughts :)

### CODE REVIEW

**Comment by BrianGilbert** [comment]
@Uzay-G I'm sorry, but I can't really tell how it works from the static image?

**Comment by Uzay-G** [comment]
Here's a gif:

random

**Comment by BrianGilbert** [comment]
It feels to me this should be hidden at first, and exposed by selecting folder actions, one of which would be the delete option. I’ll try and mock something later today

**Comment by Uzay-G** [comment]
Oh sorry I just saw this.  Do you mean a button called "folder settings" or smth where these buttons would then display?

**Comment by Uzay-G** [comment]
Merging for now, open to suggestions if you have the time to explain more though :)

**Pull request merged**
