### PR TITLE
Add main_dark.css static file, add use_theme_dark to config.THEME_CONF dict, update base.html to load alternate CSS if True

### PR DESCRIPTION
**Pull request by ropable**

### CODE REVIEW

**Comment by ropable** [comment]
This was the simplest way that I could think of to provide a baked-in alternative to the default theme. It's not that elegant (for e.g. it might need to be refactored if further themes are added). The `main_dark.css` file added has replaced most of the hard-coded CSS color values with variables, so it could also possibly be refactored to make it easier to add new themes (e.g. rename the variables for page elements rather than colors).

**Comment by ropable** [comment]
Urgh, I just noticed that the Markdown editor looks pretty awful. Stand by while I try to work out how to theme it too.

**Comment by Uzay-G** [comment]
Ooh it's really nice! I just don't really like the white / very light gray of the forms / buttons / editor / flashes. I find it doesn't really go well with the background color.

Do you have any ideas on what color we could replace it with? Otherwise I can help you with finding one :blush:

**Comment by ropable** [comment]
Thanks, it probably does need a bit more polishing yet. I'll do a bit more work tomorrow, and put a few screenshots up here for discussion.

**Comment by ropable** [comment]
@Uzay-G  Couple of concepts for darker button/form colors. Login screen:

archivy_login

Main screen with success message:

archivy_main

Data obj view:

archivy_dataobj

Editor view:

archivy_editor

**Comment by Uzay-G** [comment]
I lik it! For the first picture though, I think the login form should stay centred.

**Comment by ropable** [comment]
How about this for the login?

archivy_login

Note that to achieve this I added `width: 300px; margin: 0 auto;` to the login form (specific to a new id on that form) and altered the following generally-applicable rule for input fields further up (making it specific to just the user form using another new id tag on that form):

```css
#user-form input:not([type="checkbox"]):not([type="submit"]) {
    display: block;
}
```
I'm not 100% sure of the implications of this CSS change, but it doesn't seem to affect anything else as I've looked around.

**Comment by ropable** [comment]
I fixed a couple of too-light styles. Note that, rather than replacing the editor.css and markdown.css for the dark theme, I created editor_dark.css and markdown_dark.css that are conditionally loaded in the templates. I tried to do the same for main_dark.css but the changes are more drastic and I couldn't make it with just overrides (it needs to be loaded either/or with main.css). This may be an issue for the project going forward (technical debt) as there are now two CSS files that need to be kept approximately in sync.

**Comment by Uzay-G** [comment]
Thanks for the warning! I'll try and look at it tomorrow to see how I could refactor it to prevent duplication :)

**Comment by Uzay-G** [comment]
I just rewrote it so that the main_dark.css simply overrides main.css, with the core parts simply stored in the main file.

I'll make some other minor style changes and then this should be good to merge!

**Comment by Uzay-G** [comment]
Ok I made some changes. Could you check it out and tell me if everything's fine with you?

@edditler what do you think of the theme? I'd love to hear your thoughts :blush:

**Comment by ropable** [comment]
Updates look fine to me. No issues noted in my testing.

**Comment by ropable** [comment]
@Uzay-G No issues noted with that last tweak. However, one small thing that bothers me on the dataobj template is that the "Move to" button overlaps the "Delete" button:

archivy_editbuttons

This affects both the default and the dark theme. It can be resolved by updating the rule in `main.css` to add a left-side-only margin to form elements in the `post-btns` div, like so:

```css
#post-btns form {
    margin: 0 10 0 0;
}
```

The "Move to" button is also ever-so-slightly shorter than the other two buttons (20 px compared to 21.5 px on my site). We could force all the button elements in that div to a consistent height with the following rule:

```css
#post-btns .btn {
    height: 35px;
}
```

**Comment by Uzay-G** [comment]
I implemented your nice suggestions, I'll merge this in now :)

**Pull request merged**
