### PR TITLE
 Phase out pandoc dep and enhance frontend editor

### PR DESCRIPTION
**Pull request by Uzay-G**
This PR fixes several core issues:

- Pandoc is too heavy and its usefulness does not warrant the exra dependency
- Rendering search results with Pandoc was slow, the new js markdown parser is much faster.
- Parser migration fixes security issues https://github.com/archivy/archivy/issues/151.
- Many features of Pandoc markdown were not available in the web editor, but we now use the same md -> html parser on the editor also, which fixes this.

Also has some random other fixes:

- Bug related to recent refactor of configuration that had not been detected: https://github.com/archivy/archivy/blob/3f192e19417151ab4dc5ae2d37172c402624e1de/archivy/api.py#L198 
- No longer renders empty links https://github.com/archivy/archivy/blob/3f192e19417151ab4dc5ae2d37172c402624e1de/archivy/models.py#L146-L148

Info:

`markdown-parser.html` loads the markdown parser as `window.parser`

### CODE REVIEW

**Comment by Uzay-G** [comment]
Related to #78

**Comment by Uzay-G** [comment]
This PR also adds an automatically generated table of contents and anchors for headings.

**Comment by Uzay-G** [comment]
This PR removes a 50MB requirement for pandoc, but adds the 500kB js file for the editor.

Huge improvement, but I'm wondering if we can strip things down.

@srevinsaju do you have any ideas on how to maybe decrease this?

Some of these packages are not essential to all users, the ones loaded are:

- **Essential** [markdown-it](https://github.com/markdown-it/markdown-it/) - markdown to html parser
- [markdown-it-footnote](https://github.com/markdown-it/markdown-it-footnote)
- [markdown-it-texmath](https://github.com/goessner/markdown-it-texmath/)
- [katex](https://github.com/KaTeX/KaTeX)
- [markdown-it-anchor](https://github.com/valeriangalliat/markdown-it-anchor)
- [markdown-it-toc-done-right](https://github.com/nagaozen/markdown-it-toc-done-right) table of contents for dataobjs
- [markdown-it-mark](https://github.com/markdown-it/markdown-it-mark)

Maybe we could try and smartly load only the scripts that are needed for example, check if `$$` in the dataobj content and then load the latex packages?

Same for code blocks.

**Comment by Uzay-G** [comment]
@srevinsaju could you quickly check out / review the changes for https://github.com/archivy/archivy/blob/remove_pandoc/archivy/templates/markdown-parser.html and https://github.com/archivy/archivy/blob/remove_pandoc/archivy/templates/home.html. 

Those are the main changes with the new markdown parser.

Otherwise there are some other minor changes / fixes mentioned in the body.

Here's an example of the functionality:

**Comment by Uzay-G** [comment]
@srevinsaju could you quickly check out / review the changes for https://github.com/archivy/archivy/blob/remove_pandoc/archivy/templates/markdown-parser.html and https://github.com/archivy/archivy/blob/remove_pandoc/archivy/templates/home.html. 

Those are the main changes with the new markdown parser.

Otherwise there are some other minor changes / fixes mentioned in the body.

Here's an example of the functionality:

random

**Comment by srevinsaju** [comment]
Sorry, I do not have time. Probably you will have to wait until Christmas, or you can merge this PR on your own

**Comment by Uzay-G** [comment]
Okay no problem.

**Pull request merged**
