### PR TITLE
Bidirectional tags

### PR DESCRIPTION
**Pull request by Uzay-G**
Implements bidirectional links between notes (on instances with search), fixing #119.

random

@BrianGilbert it'd be really nice if you could test out the changes :)

@srevinsaju if you have time it'd be nice if you could check the code, otherwise it's fine I can manage on my own.

### CODE REVIEW

**Comment by srevinsaju** [comment]
This contains changes from #217 too?

**Comment by Uzay-G** [comment]
> This contains changes from #217 too?

Yeah I just realised hmm. In that case @BrianGilbert @srevinsaju don't worry about this PR for now, we can look at it once #217 is merged.

**Comment by BrianGilbert** [comment]
@Uzay-G more than happy to, is there an easy way for me to test this while using the docker images?

**Comment by Uzay-G** [comment]
I'm going to open another PR identical to this one, because there was a problem with the changes relying on another PR that is now merged and github not detecting these new changes.

**Comment by Uzay-G** [comment]
Ok it seems I've fixed it on this PR, the diff is good now.

**Comment by BrianGilbert** [comment]
@Uzay-G Any info on how to test this using the docker builds?

**Comment by Uzay-G** [comment]
Oh sorry about that! I'm not sure exactly how we could get that working 🤔. It's a bit late here but I'll think about it tomorrow, but if I don't find anything @srevinsaju said he would check the pr out tomorrow and I think we'll get it merged soon (just need to add a few tests and do the review).

**Review by srevinsaju — COMMENTED** [review]
I tested it today, I am able to get the suggestions when I click "Linked tags", etc.. but then once I save the article, I am not able to go to that particular link. 

image


Does it have something to be done with https://github.com/archivy/archivy/pull/218/files#diff-82dfc4e59d32f549c0c0f2d629c4205952911a4a80a26fb4a55ba7ce94e0f66bR161 ?

**Comment by Uzay-G** [comment]
Oh right that's something I totally forgot about - I implemented the selection and the backlinks but now I need to render them. I'll tell you when it's done :)

**Comment by srevinsaju** [comment]
Cool :tada:

**Comment by Uzay-G** [comment]
Hmm I'm trying to basically add a rule to the [markdown-it](https://github.com/markdown-it/markdown-it) parser so that it parses these wiki style links.

I'm not very experienced with js and especially node modules however, and I've been trying to use this package: https://github.com/jsepia/markdown-it-wikilinks.

It's only written for npm though and I'm having some trouble converting it to something we can call from the browser :thinking:

**Comment by Uzay-G** [comment]
Ok I changed the rendering, now it should be good. @srevinsaju could you check it out :)

Then I'll add some tests for the changes.

**Comment by srevinsaju** [comment]
Sure, I will check it out tonight!

**Comment by srevinsaju** [comment]
Tested, 
image

I have two extra `[[` and `]]`, is it intentional?

**Comment by Uzay-G** [comment]
Yeah I thought it made the difference more clearer between links pointing to notes and just normal ones. (Also it resolves the annoying problem I was having with the JS parser).

**Review by srevinsaju — APPROVED** [review]
Oh, ok. Tested, reviewed. Ready for merge 🎉

**Comment by Uzay-G** [comment]
Perfect!

**Pull request merged**
