### PR TITLE
Update my previous commit authoring and add .idea in gitignore

### PR DESCRIPTION
**Pull request by mmozos**

### CODE REVIEW

**Comment by Uzay-G** [comment]
What is this? I'm going to close because no description is provided and this PR doesn't make sense.

**Comment by mmozos** [comment]
Ok, was trying to amend my username commit but did not realized was wrong way.

**Comment by Uzay-G** [comment]
What exactly are you trying to do? Maybe I can help.

**Comment by mmozos** [comment]
Look here: https://github.com/mmozos/archivy/commits?author=mmozos
And the second one here: https://github.com/mmozos/archivy/commits/master/archivy/cli.py

By recreating my GitHub account have lost some contribution atributions, will try with [this answer](https://stackoverflow.com/a/28845565).

My new account data is: mmozos <martinmozos@gmail.com>

**Comment by Uzay-G** [comment]
Ah ok, I see.

Good luck!

**Pull request closed without merging**
