### PR TITLE
highlight.js 10.4.1 -> 11.0.1 + more languages

### PR DESCRIPTION
**Pull request by Bahnschrift**
This does increase the filesize from 112kb to ~1mb, but it also adds support for ~160 more languages.

### CODE REVIEW

**Comment by Uzay-G** [comment]
Hmm, that is a significant size increase.

I'll think about it. Out of curiosity, what language were you missing?

**Comment by Bahnschrift** [comment]
I was missing F#, Crystal and Go. I should note that I didn't see any loading time increases with the larger file.

**Comment by Bahnschrift** [comment]
I wonder if a better solution could be to include the full highlight.js package instead of the .min.js so the languages would only be stored in their own files and only loaded when needed. Looks to still be around the same size all up with that approach.

**Comment by Uzay-G** [comment]
How would it work in that case? Are they conditionally loaded or something?

**Comment by Uzay-G** [comment]
Why did you close?

**Pull request closed without merging**
